package idv.caemasar.documentCenter.entity;
// Generated 2017-5-11 2:20:14 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * DcTDepartments generated by hbm2java
 */
public class DcTDepartments implements java.io.Serializable {

	private Integer deptId;
	private String deptNumber;
	private String deptName;
	private String deptSuper;
	private Set dcTUserses = new HashSet(0);

	public DcTDepartments() {
	}

	public DcTDepartments(String deptNumber, String deptName, String deptSuper, Set dcTUserses) {
		this.deptNumber = deptNumber;
		this.deptName = deptName;
		this.deptSuper = deptSuper;
		this.dcTUserses = dcTUserses;
	}

	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	public String getDeptNumber() {
		return this.deptNumber;
	}

	public void setDeptNumber(String deptNumber) {
		this.deptNumber = deptNumber;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getDeptSuper() {
		return this.deptSuper;
	}

	public void setDeptSuper(String deptSuper) {
		this.deptSuper = deptSuper;
	}

	public Set getDcTUserses() {
		return this.dcTUserses;
	}

	public void setDcTUserses(Set dcTUserses) {
		this.dcTUserses = dcTUserses;
	}

}
