package idv.caemasar.documentCenter.entity;
// Generated 2017-5-11 2:20:14 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DcTFiles generated by hbm2java
 */
public class DcTFiles implements java.io.Serializable {

	private Integer flieId;
	private DcTDirectories dcTDirectories;
	private DcTUsers dcTUsers;
	private String fileFilename;
	private Double fileSize;
	private Date fileUploadtime;
	private Integer fileType;
	private Set dcTFileLogs = new HashSet(0);
	private Set dcTShareboxses = new HashSet(0);

	public DcTFiles() {
	}

	public DcTFiles(DcTDirectories dcTDirectories, DcTUsers dcTUsers, String fileFilename, Double fileSize,
			Date fileUploadtime, Integer fileType, Set dcTFileLogs, Set dcTShareboxses) {
		this.dcTDirectories = dcTDirectories;
		this.dcTUsers = dcTUsers;
		this.fileFilename = fileFilename;
		this.fileSize = fileSize;
		this.fileUploadtime = fileUploadtime;
		this.fileType = fileType;
		this.dcTFileLogs = dcTFileLogs;
		this.dcTShareboxses = dcTShareboxses;
	}

	public Integer getFlieId() {
		return this.flieId;
	}

	public void setFlieId(Integer flieId) {
		this.flieId = flieId;
	}

	public DcTDirectories getDcTDirectories() {
		return this.dcTDirectories;
	}

	public void setDcTDirectories(DcTDirectories dcTDirectories) {
		this.dcTDirectories = dcTDirectories;
	}

	public DcTUsers getDcTUsers() {
		return this.dcTUsers;
	}

	public void setDcTUsers(DcTUsers dcTUsers) {
		this.dcTUsers = dcTUsers;
	}

	public String getFileFilename() {
		return this.fileFilename;
	}

	public void setFileFilename(String fileFilename) {
		this.fileFilename = fileFilename;
	}

	public Double getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Double fileSize) {
		this.fileSize = fileSize;
	}

	public Date getFileUploadtime() {
		return this.fileUploadtime;
	}

	public void setFileUploadtime(Date fileUploadtime) {
		this.fileUploadtime = fileUploadtime;
	}

	public Integer getFileType() {
		return this.fileType;
	}

	public void setFileType(Integer fileType) {
		this.fileType = fileType;
	}

	public Set getDcTFileLogs() {
		return this.dcTFileLogs;
	}

	public void setDcTFileLogs(Set dcTFileLogs) {
		this.dcTFileLogs = dcTFileLogs;
	}

	public Set getDcTShareboxses() {
		return this.dcTShareboxses;
	}

	public void setDcTShareboxses(Set dcTShareboxses) {
		this.dcTShareboxses = dcTShareboxses;
	}

}
