package idv.caemasar.documentCenter.entity;
// Generated 2017-5-11 2:20:14 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * DcTFileLog generated by hbm2java
 */
public class DcTFileLog implements java.io.Serializable {

	private Integer flogId;
	private DcTFiles dcTFiles;
	private DcTUsers dcTUsers;
	private Date flogTime;
	private String flogOperation;

	public DcTFileLog() {
	}

	public DcTFileLog(DcTFiles dcTFiles, DcTUsers dcTUsers, Date flogTime, String flogOperation) {
		this.dcTFiles = dcTFiles;
		this.dcTUsers = dcTUsers;
		this.flogTime = flogTime;
		this.flogOperation = flogOperation;
	}

	public Integer getFlogId() {
		return this.flogId;
	}

	public void setFlogId(Integer flogId) {
		this.flogId = flogId;
	}

	public DcTFiles getDcTFiles() {
		return this.dcTFiles;
	}

	public void setDcTFiles(DcTFiles dcTFiles) {
		this.dcTFiles = dcTFiles;
	}

	public DcTUsers getDcTUsers() {
		return this.dcTUsers;
	}

	public void setDcTUsers(DcTUsers dcTUsers) {
		this.dcTUsers = dcTUsers;
	}

	public Date getFlogTime() {
		return this.flogTime;
	}

	public void setFlogTime(Date flogTime) {
		this.flogTime = flogTime;
	}

	public String getFlogOperation() {
		return this.flogOperation;
	}

	public void setFlogOperation(String flogOperation) {
		this.flogOperation = flogOperation;
	}

}
