package idv.caemasar.documentCenter.entity;
// Generated 2017-5-11 2:20:14 by Hibernate Tools 4.3.5.Final

/**
 * DcTGroupsUsers generated by hbm2java
 */
public class DcTGroupsUsers implements java.io.Serializable {

	private Integer guId;
	private DcTGroups dcTGroups;
	private DcTUsers dcTUsers;

	public DcTGroupsUsers() {
	}

	public DcTGroupsUsers(DcTGroups dcTGroups, DcTUsers dcTUsers) {
		this.dcTGroups = dcTGroups;
		this.dcTUsers = dcTUsers;
	}

	public Integer getGuId() {
		return this.guId;
	}

	public void setGuId(Integer guId) {
		this.guId = guId;
	}

	public DcTGroups getDcTGroups() {
		return this.dcTGroups;
	}

	public void setDcTGroups(DcTGroups dcTGroups) {
		this.dcTGroups = dcTGroups;
	}

	public DcTUsers getDcTUsers() {
		return this.dcTUsers;
	}

	public void setDcTUsers(DcTUsers dcTUsers) {
		this.dcTUsers = dcTUsers;
	}

}
