package idv.caemasar.documentCenter.entity;
// Generated 2017-5-11 2:20:14 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * DcTGroups generated by hbm2java
 */
public class DcTGroups implements java.io.Serializable {

	private Integer groupId;
	private String groupName;
	private Set dcTGroupsUserses = new HashSet(0);
	private Set dcTGroupsPermissionses = new HashSet(0);

	public DcTGroups() {
	}

	public DcTGroups(String groupName, Set dcTGroupsUserses, Set dcTGroupsPermissionses) {
		this.groupName = groupName;
		this.dcTGroupsUserses = dcTGroupsUserses;
		this.dcTGroupsPermissionses = dcTGroupsPermissionses;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Set getDcTGroupsUserses() {
		return this.dcTGroupsUserses;
	}

	public void setDcTGroupsUserses(Set dcTGroupsUserses) {
		this.dcTGroupsUserses = dcTGroupsUserses;
	}

	public Set getDcTGroupsPermissionses() {
		return this.dcTGroupsPermissionses;
	}

	public void setDcTGroupsPermissionses(Set dcTGroupsPermissionses) {
		this.dcTGroupsPermissionses = dcTGroupsPermissionses;
	}

}
