package idv.caemasar.documentCenter.entity;
// Generated 2017-5-11 2:20:14 by Hibernate Tools 4.3.5.Final

/**
 * DcTGroupsPermissions generated by hbm2java
 */
public class DcTGroupsPermissions implements java.io.Serializable {

	private Integer gpId;
	private DcTGroups dcTGroups;
	private DcTPermissions dcTPermissions;

	public DcTGroupsPermissions() {
	}

	public DcTGroupsPermissions(DcTGroups dcTGroups, DcTPermissions dcTPermissions) {
		this.dcTGroups = dcTGroups;
		this.dcTPermissions = dcTPermissions;
	}

	public Integer getGpId() {
		return this.gpId;
	}

	public void setGpId(Integer gpId) {
		this.gpId = gpId;
	}

	public DcTGroups getDcTGroups() {
		return this.dcTGroups;
	}

	public void setDcTGroups(DcTGroups dcTGroups) {
		this.dcTGroups = dcTGroups;
	}

	public DcTPermissions getDcTPermissions() {
		return this.dcTPermissions;
	}

	public void setDcTPermissions(DcTPermissions dcTPermissions) {
		this.dcTPermissions = dcTPermissions;
	}

}
