package idv.caemasar.documentCenter.entity;
// Generated 2017-5-11 2:20:14 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * DcTMails generated by hbm2java
 */
public class DcTMails implements java.io.Serializable {

	private Integer mailId;
	private DcTUsers dcTUsersByMailFromUserid;
	private DcTUsers dcTUsersByMailToUserid;
	private Date mailSendtime;
	private String mailLetter;

	public DcTMails() {
	}

	public DcTMails(DcTUsers dcTUsersByMailFromUserid, DcTUsers dcTUsersByMailToUserid, Date mailSendtime,
			String mailLetter) {
		this.dcTUsersByMailFromUserid = dcTUsersByMailFromUserid;
		this.dcTUsersByMailToUserid = dcTUsersByMailToUserid;
		this.mailSendtime = mailSendtime;
		this.mailLetter = mailLetter;
	}

	public Integer getMailId() {
		return this.mailId;
	}

	public void setMailId(Integer mailId) {
		this.mailId = mailId;
	}

	public DcTUsers getDcTUsersByMailFromUserid() {
		return this.dcTUsersByMailFromUserid;
	}

	public void setDcTUsersByMailFromUserid(DcTUsers dcTUsersByMailFromUserid) {
		this.dcTUsersByMailFromUserid = dcTUsersByMailFromUserid;
	}

	public DcTUsers getDcTUsersByMailToUserid() {
		return this.dcTUsersByMailToUserid;
	}

	public void setDcTUsersByMailToUserid(DcTUsers dcTUsersByMailToUserid) {
		this.dcTUsersByMailToUserid = dcTUsersByMailToUserid;
	}

	public Date getMailSendtime() {
		return this.mailSendtime;
	}

	public void setMailSendtime(Date mailSendtime) {
		this.mailSendtime = mailSendtime;
	}

	public String getMailLetter() {
		return this.mailLetter;
	}

	public void setMailLetter(String mailLetter) {
		this.mailLetter = mailLetter;
	}

}
