package idv.caemasar.documentCenter.entity;
// Generated 2017-5-11 2:20:14 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * DcTPermissions generated by hbm2java
 */
public class DcTPermissions implements java.io.Serializable {

	private Integer perId;
	private String perPermission;
	private String perDescpt;
	private String perCategory;
	private Set dcTGroupsPermissionses = new HashSet(0);
	private Set dcTUsersPermissionses = new HashSet(0);

	public DcTPermissions() {
	}

	public DcTPermissions(String perPermission, String perDescpt, String perCategory, Set dcTGroupsPermissionses,
			Set dcTUsersPermissionses) {
		this.perPermission = perPermission;
		this.perDescpt = perDescpt;
		this.perCategory = perCategory;
		this.dcTGroupsPermissionses = dcTGroupsPermissionses;
		this.dcTUsersPermissionses = dcTUsersPermissionses;
	}

	public Integer getPerId() {
		return this.perId;
	}

	public void setPerId(Integer perId) {
		this.perId = perId;
	}

	public String getPerPermission() {
		return this.perPermission;
	}

	public void setPerPermission(String perPermission) {
		this.perPermission = perPermission;
	}

	public String getPerDescpt() {
		return this.perDescpt;
	}

	public void setPerDescpt(String perDescpt) {
		this.perDescpt = perDescpt;
	}

	public String getPerCategory() {
		return this.perCategory;
	}

	public void setPerCategory(String perCategory) {
		this.perCategory = perCategory;
	}

	public Set getDcTGroupsPermissionses() {
		return this.dcTGroupsPermissionses;
	}

	public void setDcTGroupsPermissionses(Set dcTGroupsPermissionses) {
		this.dcTGroupsPermissionses = dcTGroupsPermissionses;
	}

	public Set getDcTUsersPermissionses() {
		return this.dcTUsersPermissionses;
	}

	public void setDcTUsersPermissionses(Set dcTUsersPermissionses) {
		this.dcTUsersPermissionses = dcTUsersPermissionses;
	}

}
