package idv.caemasar.documentCenter.entity;
// Generated 2017-5-11 2:20:14 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * DcTShareboxs generated by hbm2java
 */
public class DcTShareboxs implements java.io.Serializable {

	private Integer shareId;
	private DcTFiles dcTFiles;
	private DcTUsers dcTUsersByShareFromUserid;
	private DcTUsers dcTUsersByShareToUserid;
	private Date shareSendtime;

	public DcTShareboxs() {
	}

	public DcTShareboxs(DcTFiles dcTFiles, DcTUsers dcTUsersByShareFromUserid, DcTUsers dcTUsersByShareToUserid,
			Date shareSendtime) {
		this.dcTFiles = dcTFiles;
		this.dcTUsersByShareFromUserid = dcTUsersByShareFromUserid;
		this.dcTUsersByShareToUserid = dcTUsersByShareToUserid;
		this.shareSendtime = shareSendtime;
	}

	public Integer getShareId() {
		return this.shareId;
	}

	public void setShareId(Integer shareId) {
		this.shareId = shareId;
	}

	public DcTFiles getDcTFiles() {
		return this.dcTFiles;
	}

	public void setDcTFiles(DcTFiles dcTFiles) {
		this.dcTFiles = dcTFiles;
	}

	public DcTUsers getDcTUsersByShareFromUserid() {
		return this.dcTUsersByShareFromUserid;
	}

	public void setDcTUsersByShareFromUserid(DcTUsers dcTUsersByShareFromUserid) {
		this.dcTUsersByShareFromUserid = dcTUsersByShareFromUserid;
	}

	public DcTUsers getDcTUsersByShareToUserid() {
		return this.dcTUsersByShareToUserid;
	}

	public void setDcTUsersByShareToUserid(DcTUsers dcTUsersByShareToUserid) {
		this.dcTUsersByShareToUserid = dcTUsersByShareToUserid;
	}

	public Date getShareSendtime() {
		return this.shareSendtime;
	}

	public void setShareSendtime(Date shareSendtime) {
		this.shareSendtime = shareSendtime;
	}

}
