package idv.caemasar.documentCenter.entity;
// Generated 2017-5-11 2:20:14 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * DcTUserLog generated by hbm2java
 */
public class DcTUserLog implements java.io.Serializable {

	private Integer ulogId;
	private DcTUsers dcTUsers;
	private Date ulogTime;
	private String ulogIp;

	public DcTUserLog() {
	}

	public DcTUserLog(DcTUsers dcTUsers, Date ulogTime, String ulogIp) {
		this.dcTUsers = dcTUsers;
		this.ulogTime = ulogTime;
		this.ulogIp = ulogIp;
	}

	public Integer getUlogId() {
		return this.ulogId;
	}

	public void setUlogId(Integer ulogId) {
		this.ulogId = ulogId;
	}

	public DcTUsers getDcTUsers() {
		return this.dcTUsers;
	}

	public void setDcTUsers(DcTUsers dcTUsers) {
		this.dcTUsers = dcTUsers;
	}

	public Date getUlogTime() {
		return this.ulogTime;
	}

	public void setUlogTime(Date ulogTime) {
		this.ulogTime = ulogTime;
	}

	public String getUlogIp() {
		return this.ulogIp;
	}

	public void setUlogIp(String ulogIp) {
		this.ulogIp = ulogIp;
	}

}
