package idv.caemasar.documentCenter.entity;
// Generated 2017-5-11 2:20:14 by Hibernate Tools 4.3.5.Final

/**
 * DcTUsersPermissions generated by hbm2java
 */
public class DcTUsersPermissions implements java.io.Serializable {

	private Integer upId;
	private DcTPermissions dcTPermissions;
	private DcTUsers dcTUsers;

	public DcTUsersPermissions() {
	}

	public DcTUsersPermissions(DcTPermissions dcTPermissions, DcTUsers dcTUsers) {
		this.dcTPermissions = dcTPermissions;
		this.dcTUsers = dcTUsers;
	}

	public Integer getUpId() {
		return this.upId;
	}

	public void setUpId(Integer upId) {
		this.upId = upId;
	}

	public DcTPermissions getDcTPermissions() {
		return this.dcTPermissions;
	}

	public void setDcTPermissions(DcTPermissions dcTPermissions) {
		this.dcTPermissions = dcTPermissions;
	}

	public DcTUsers getDcTUsers() {
		return this.dcTUsers;
	}

	public void setDcTUsers(DcTUsers dcTUsers) {
		this.dcTUsers = dcTUsers;
	}

}
