package idv.caemasar.documentCenter.entity;
// Generated 2017-5-11 2:20:14 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * DcTUsers generated by hbm2java
 */
public class DcTUsers implements java.io.Serializable {

	private Integer UId;
	private DcTDepartments dcTDepartments;
	private String UUsername;
	private String UPassword;
	private String URealname;
	private String UEmail;
	private String UPhone;
	private Integer UIdentity;
	private Set dcTMailsesForMailFromUserid = new HashSet(0);
	private Set dcTMailsesForMailToUserid = new HashSet(0);
	private Set dcTShareboxsesForShareFromUserid = new HashSet(0);
	private Set dcTFileLogs = new HashSet(0);
	private Set dcTDirectoryLogs = new HashSet(0);
	private Set dcTShareboxsesForShareToUserid = new HashSet(0);
	private Set dcTGroupsUserses = new HashSet(0);
	private Set dcTUsersPermissionses = new HashSet(0);
	private Set dcTDirectorieses = new HashSet(0);
	private Set dcTFileses = new HashSet(0);
	private Set dcTUserLogs = new HashSet(0);

	public DcTUsers() {
	}

	public DcTUsers(DcTDepartments dcTDepartments, String UUsername, String UPassword, String URealname, String UEmail,
			String UPhone, Integer UIdentity, Set dcTMailsesForMailFromUserid, Set dcTMailsesForMailToUserid,
			Set dcTShareboxsesForShareFromUserid, Set dcTFileLogs, Set dcTDirectoryLogs,
			Set dcTShareboxsesForShareToUserid, Set dcTGroupsUserses, Set dcTUsersPermissionses, Set dcTDirectorieses,
			Set dcTFileses, Set dcTUserLogs) {
		this.dcTDepartments = dcTDepartments;
		this.UUsername = UUsername;
		this.UPassword = UPassword;
		this.URealname = URealname;
		this.UEmail = UEmail;
		this.UPhone = UPhone;
		this.UIdentity = UIdentity;
		this.dcTMailsesForMailFromUserid = dcTMailsesForMailFromUserid;
		this.dcTMailsesForMailToUserid = dcTMailsesForMailToUserid;
		this.dcTShareboxsesForShareFromUserid = dcTShareboxsesForShareFromUserid;
		this.dcTFileLogs = dcTFileLogs;
		this.dcTDirectoryLogs = dcTDirectoryLogs;
		this.dcTShareboxsesForShareToUserid = dcTShareboxsesForShareToUserid;
		this.dcTGroupsUserses = dcTGroupsUserses;
		this.dcTUsersPermissionses = dcTUsersPermissionses;
		this.dcTDirectorieses = dcTDirectorieses;
		this.dcTFileses = dcTFileses;
		this.dcTUserLogs = dcTUserLogs;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public DcTDepartments getDcTDepartments() {
		return this.dcTDepartments;
	}

	public void setDcTDepartments(DcTDepartments dcTDepartments) {
		this.dcTDepartments = dcTDepartments;
	}

	public String getUUsername() {
		return this.UUsername;
	}

	public void setUUsername(String UUsername) {
		this.UUsername = UUsername;
	}

	public String getUPassword() {
		return this.UPassword;
	}

	public void setUPassword(String UPassword) {
		this.UPassword = UPassword;
	}

	public String getURealname() {
		return this.URealname;
	}

	public void setURealname(String URealname) {
		this.URealname = URealname;
	}

	public String getUEmail() {
		return this.UEmail;
	}

	public void setUEmail(String UEmail) {
		this.UEmail = UEmail;
	}

	public String getUPhone() {
		return this.UPhone;
	}

	public void setUPhone(String UPhone) {
		this.UPhone = UPhone;
	}

	public Integer getUIdentity() {
		return this.UIdentity;
	}

	public void setUIdentity(Integer UIdentity) {
		this.UIdentity = UIdentity;
	}

	public Set getDcTMailsesForMailFromUserid() {
		return this.dcTMailsesForMailFromUserid;
	}

	public void setDcTMailsesForMailFromUserid(Set dcTMailsesForMailFromUserid) {
		this.dcTMailsesForMailFromUserid = dcTMailsesForMailFromUserid;
	}

	public Set getDcTMailsesForMailToUserid() {
		return this.dcTMailsesForMailToUserid;
	}

	public void setDcTMailsesForMailToUserid(Set dcTMailsesForMailToUserid) {
		this.dcTMailsesForMailToUserid = dcTMailsesForMailToUserid;
	}

	public Set getDcTShareboxsesForShareFromUserid() {
		return this.dcTShareboxsesForShareFromUserid;
	}

	public void setDcTShareboxsesForShareFromUserid(Set dcTShareboxsesForShareFromUserid) {
		this.dcTShareboxsesForShareFromUserid = dcTShareboxsesForShareFromUserid;
	}

	public Set getDcTFileLogs() {
		return this.dcTFileLogs;
	}

	public void setDcTFileLogs(Set dcTFileLogs) {
		this.dcTFileLogs = dcTFileLogs;
	}

	public Set getDcTDirectoryLogs() {
		return this.dcTDirectoryLogs;
	}

	public void setDcTDirectoryLogs(Set dcTDirectoryLogs) {
		this.dcTDirectoryLogs = dcTDirectoryLogs;
	}

	public Set getDcTShareboxsesForShareToUserid() {
		return this.dcTShareboxsesForShareToUserid;
	}

	public void setDcTShareboxsesForShareToUserid(Set dcTShareboxsesForShareToUserid) {
		this.dcTShareboxsesForShareToUserid = dcTShareboxsesForShareToUserid;
	}

	public Set getDcTGroupsUserses() {
		return this.dcTGroupsUserses;
	}

	public void setDcTGroupsUserses(Set dcTGroupsUserses) {
		this.dcTGroupsUserses = dcTGroupsUserses;
	}

	public Set getDcTUsersPermissionses() {
		return this.dcTUsersPermissionses;
	}

	public void setDcTUsersPermissionses(Set dcTUsersPermissionses) {
		this.dcTUsersPermissionses = dcTUsersPermissionses;
	}

	public Set getDcTDirectorieses() {
		return this.dcTDirectorieses;
	}

	public void setDcTDirectorieses(Set dcTDirectorieses) {
		this.dcTDirectorieses = dcTDirectorieses;
	}

	public Set getDcTFileses() {
		return this.dcTFileses;
	}

	public void setDcTFileses(Set dcTFileses) {
		this.dcTFileses = dcTFileses;
	}

	public Set getDcTUserLogs() {
		return this.dcTUserLogs;
	}

	public void setDcTUserLogs(Set dcTUserLogs) {
		this.dcTUserLogs = dcTUserLogs;
	}

}
