package idv.caemasar.documentCenter.entity;
// Generated 2017-5-11 2:20:14 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * DcTMails generated by hbm2java
 */
public class Mail implements java.io.Serializable {

	private Integer mail_id;
	private Integer mail_from_userid;
	private String mail_from_username;
	private Integer mail_to_userid;
	private String mail_to_username;
	private Date mail_sendtime;
	private String mail_letter;

	public Mail() {
	}

	public Mail(Integer mail_id, Integer mail_from_userid, Integer mail_to_userid, Date mail_sendtime,
			String mail_letter) {
		this.mail_id = mail_id;
		this.mail_from_userid = mail_from_userid;
		this.mail_to_userid = mail_to_userid;
		this.mail_sendtime = mail_sendtime;
		this.mail_letter = mail_letter;
	}

	public Integer getMail_id() {
		return mail_id;
	}

	public void setMail_id(Integer mail_id) {
		this.mail_id = mail_id;
	}

	public Integer getMail_from_userid() {
		return mail_from_userid;
	}

	public void setMail_from_userid(Integer mail_from_userid) {
		this.mail_from_userid = mail_from_userid;
	}

	public Integer getMail_to_userid() {
		return mail_to_userid;
	}

	public void setMail_to_userid(Integer mail_to_userid) {
		this.mail_to_userid = mail_to_userid;
	}

	public Date getMail_sendtime() {
		return mail_sendtime;
	}

	public void setMail_sendtime(Date mail_sendtime) {
		this.mail_sendtime = mail_sendtime;
	}

	public String getMail_letter() {
		return mail_letter;
	}

	public void setMail_letter(String mail_letter) {
		this.mail_letter = mail_letter;
	}

	public String getMail_from_username() {
		return mail_from_username;
	}

	public void setMail_from_username(String mail_from_username) {
		this.mail_from_username = mail_from_username;
	}

	public String getMail_to_username() {
		return mail_to_username;
	}

	public void setMail_to_username(String mail_to_username) {
		this.mail_to_username = mail_to_username;
	}

	@Override
	public String toString() {
		return "Mail [mail_id=" + mail_id + ", mail_from_userid=" + mail_from_userid + ", mail_to_userid="
				+ mail_to_userid + ", mail_sendtime=" + mail_sendtime + ", mail_letter=" + mail_letter + "]";
	}

}
